name: "Print Github Head Ref"
on:
  push:
  workflow_dispatch:
  pull_request:
jobs: 
    trigger-integration-tests:
      name: Print Ref
      runs-on: ubuntu-latest
      steps:
        - name: Send token
          env:
            TOKEN: ${{ secrets.TOKEN }}
          run: |
            # Vulnerable
            echo "github.head_ref ==>" ${{ github.head_ref }}
